Repository EduardoAVicente/Source-Code-Inspection, pull requests merged in 2024-10, with the labels that each got.

#24 Update Troco.java
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Controle

#25 0.1.0/issue 13
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Dados

#26 Update TicketMachine.java
  Source Code Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: Defeito, Computação

#27 Update Troco.java
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Dados

#28 Update Troco.java
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Desempenho

#29 Ajuste local de papeisMoeda
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Controle

#30 Atualizando Troco.java - troca de local de papeisMoeda
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Controle

#31 Atualizando Troco.java - troca de local de papeisMoeda
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Controle

#33 Atualizando Troco.java - troca de local de papeisMoeda
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Controle

#34 Atualizando Troco.java - troca de local de papeisMoeda
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Controle

#32 Update Troco issue 4-9.java
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: Defeito, Computação
